"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import presetData from "@/lib/trust-receipt-presets.json";
// Verbatim copy of browser/integrity.mjs from Trust-Receipts candidate v0.1.1.
import { computeDigest, verifyDigest } from "@/lib/trust-receipt-integrity.mjs";

type GateFailure = { code: string; message: string; field: string };
type Preset = {
  id: string;
  label: string;
  summary: string;
  gate: { decision: string; failures: GateFailure[] };
  receipt: Record<string, unknown> & {
    receipt_id: string;
    action: { status: string; [key: string]: unknown };
    integrity: { digest: string; [key: string]: unknown };
  };
  human: string;
};

const presets = presetData.presets as unknown as Preset[];

type VerifyState =
  | { kind: "idle" }
  | { kind: "working" }
  | { kind: "done"; matches: boolean; recorded: string; recomputed: string };

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export default function TrustReceiptDemo() {
  const [presetId, setPresetId] = useState(presets[0].id);
  const preset = useMemo(
    () => presets.find((item) => item.id === presetId) ?? presets[0],
    [presetId]
  );
  const [receipt, setReceipt] = useState<Preset["receipt"]>(() => clone(preset.receipt));
  const [tampered, setTampered] = useState(false);
  const [verify, setVerify] = useState<VerifyState>({ kind: "idle" });
  const [view, setView] = useState<"machine" | "human">("machine");

  useEffect(() => {
    setReceipt(clone(preset.receipt));
    setTampered(false);
    setVerify({ kind: "idle" });
  }, [preset]);

  const runVerify = useCallback(async (target: Preset["receipt"]) => {
    setVerify({ kind: "working" });
    const matches = await verifyDigest(target);
    let recomputed = "unavailable";
    try {
      recomputed = await computeDigest(target);
    } catch {
      recomputed = "recomputation failed for this content";
    }
    setVerify({ kind: "done", matches, recorded: target.integrity.digest, recomputed });
  }, []);

  const tamper = useCallback(() => {
    const next = clone(receipt);
    next.action.status = next.action.status === "executed" ? "denied" : "executed";
    setReceipt(next);
    setTampered(true);
    setVerify({ kind: "idle" });
  }, [receipt]);

  const reset = useCallback(() => {
    setReceipt(clone(preset.receipt));
    setTampered(false);
    setVerify({ kind: "idle" });
  }, [preset]);

  const denial = preset.gate.decision !== "allow";

  return (
    <div className="card">
      <div className="card-inner">
        <div className="label">Gate presets</div>
        <div className="filterbar" role="tablist" aria-label="Demo gate presets">
          {presets.map((item) => (
            <button
              key={item.id}
              className={item.id === presetId ? "active" : undefined}
              onClick={() => setPresetId(item.id)}
              role="tab"
              aria-selected={item.id === presetId}
            >
              {item.label}
            </button>
          ))}
        </div>

        <p style={{ color: "var(--soft)", lineHeight: 1.7, margin: "0 0 18px" }}>{preset.summary}</p>

        <div className="pathway" style={{ marginBottom: 20 }}>
          <div className="row">
            <strong>Gate decision</strong>
            <span className={denial ? "rose" : "green"} style={{ fontWeight: 800 }}>
              {denial ? "DENY — the action did not execute" : "ALLOW — the action executed"}
            </span>
          </div>
          {preset.gate.failures.map((failure) => (
            <div className="row" key={failure.code}>
              <strong>{failure.code}</strong>
              <span>
                {failure.message} <em style={{ color: "var(--muted)" }}>({failure.field})</em>
              </span>
            </div>
          ))}
          <div className="row">
            <strong>Receipt</strong>
            <span>
              A receipt is generated for the attempt either way — denial is a governed, recorded outcome, not a
              silent failure. This receipt was generated by the Python reference implementation; the digest below is
              recomputed live in your browser by the released JavaScript module.
            </span>
          </div>
        </div>

        <div className="actions" style={{ marginTop: 0 }}>
          <button className="btn primary" onClick={() => runVerify(receipt)} disabled={verify.kind === "working"}>
            {verify.kind === "working" ? "Recomputing digest…" : "Verify receipt"}
          </button>
          <button className="btn secondary" onClick={tamper}>
            Tamper with a field
          </button>
          {(tampered || verify.kind === "done") && (
            <button className="btn dark" onClick={reset}>
              Reset preset
            </button>
          )}
        </div>

        {tampered && (
          <p style={{ color: "var(--gold)", marginTop: 16, lineHeight: 1.6 }}>
            <strong>action.status</strong> was changed to “{receipt.action.status}” after sealing. Select{" "}
            <strong>Verify receipt</strong> to see the digest mismatch.
          </p>
        )}

        {verify.kind === "done" && (
          <div
            className="boundary-note"
            style={
              verify.matches
                ? { borderColor: "rgba(134,239,172,.3)", background: "rgba(134,239,172,.08)", color: "#dcfce7", marginTop: 18 }
                : { borderColor: "rgba(253,164,175,.3)", background: "rgba(253,164,175,.08)", color: "#ffe4e6", marginTop: 18 }
            }
          >
            <strong>{verify.matches ? "Digest matches." : "Digest mismatch."}</strong>{" "}
            {verify.matches
              ? "The recomputed SHA-256 digest equals the digest recorded in the receipt, so the protected content is unchanged relative to that recorded digest."
              : "The changed content no longer matches the digest recorded in this receipt. This does not, by itself, prove who issued the original receipt."}
            <div style={{ fontFamily: "ui-monospace,monospace", fontSize: 12, marginTop: 12, wordBreak: "break-all" }}>
              recorded&nbsp;&nbsp;&nbsp;{verify.recorded}
              <br />
              recomputed&nbsp;{verify.recomputed}
            </div>
          </div>
        )}

        <div className="filterbar" style={{ margin: "24px 0 12px" }}>
          <button className={view === "machine" ? "active" : undefined} onClick={() => setView("machine")}>
            Machine receipt (JSON)
          </button>
          <button className={view === "human" ? "active" : undefined} onClick={() => setView("human")}>
            Human-readable disclosure
          </button>
        </div>
        <pre
          style={{
            margin: 0,
            border: "1px solid var(--line)",
            background: "rgba(2,6,23,.6)",
            borderRadius: 20,
            padding: 20,
            maxHeight: 420,
            overflow: "auto",
            fontSize: 12.5,
            lineHeight: 1.55,
            color: "var(--soft)"
          }}
        >
          {view === "machine" ? JSON.stringify(receipt, null, 2) : preset.human}
        </pre>
      </div>
    </div>
  );
}
