import type { Metadata } from "next";
import TrustReceiptDemo from "@/components/TrustReceiptDemo";

const repoUrl = "https://github.com/emotionalinfrastructure/Trust-Receipts";
const releaseUrl = `${repoUrl}/releases/tag/v0.1.1`;
const reviewIssueUrl = `${repoUrl}/issues/4`;
const specUrl = `${repoUrl}/blob/main/docs/Trust_Receipt_Technical_Specification_v0.1.1.md`;
const claimsUrl = `${repoUrl}/blob/main/docs/PUBLIC_CLAIMS.md`;

export const metadata: Metadata = {
  title: "AI Trust Receipt — Live Demo | Emotional Infrastructure",
  description:
    "Interactive demo of the AI Trust Receipt candidate v0.1.1: six gate presets, live SHA-256 digest verification in the browser, and tamper-evidence demonstration."
};

export default function TrustReceiptPage() {
  return (
    <main id="main">
      <section className="page-title">
        <div className="container">
          <div className="kicker">Live demo · Candidate v0.1.1</div>
          <h1 style={{ fontSize: "clamp(38px,5.4vw,68px)" }}>AI Trust Receipt</h1>
          <p className="lead">
            A candidate governance specification and reference implementation for durable, user-legible,
            machine-verifiable records of consequential AI actions — gated by twelve noncompensatory requirements
            before a consequential action executes.
          </p>
          <div className="actions">
            <a className="btn primary" href={releaseUrl}>
              View the public release on GitHub →
            </a>
            <a className="btn secondary" href={reviewIssueUrl}>
              Request for Review: break this specification
            </a>
            <a className="btn secondary" href={specUrl}>
              Read the technical specification
            </a>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="two" style={{ marginBottom: 34 }}>
            <div>
              <div className="kicker">Interactive demo</div>
              <h2>Six gate presets. One governed flow.</h2>
            </div>
            <div className="copy">
              <p>
                Choose one of six interactive gate presets. The clean preset produces an allowed receipt; expired
                authority, out-of-scope action, missing review, stale evidence, and unavailable remedy presets
                produce denial receipts. These presets are distinct from the nine conformance vectors bundled with
                the release.
              </p>
              <p>
                Leave the demo on the clean execution scenario; the receipt is generated automatically. Select{" "}
                <strong>Verify receipt</strong> to recompute the digest. Then select{" "}
                <strong>Tamper with a field</strong> and verify again. The mismatch shows that the changed content
                no longer matches the digest recorded in that receipt. It does not, by itself, prove who issued the
                original receipt.
              </p>
            </div>
          </div>
          <TrustReceiptDemo />
        </div>
      </section>

      <section className="section alt">
        <div className="container two">
          <div>
            <div className="kicker">How the demo is built</div>
            <h2>Cross-runtime parity, stated precisely.</h2>
          </div>
          <div className="copy">
            <p>
              The browser demo implements the same restricted canonicalization and SHA-256 digest semantics as the
              Python reference implementation. A bundled cross-runtime test confirms the same expected digest for
              identical fixed fixtures. This demonstrates content-integrity parity within the documented input
              domain; it does not authenticate the issuer.
            </p>
            <p>
              The six receipts on this page were generated by the released Python reference implementation from
              controlled variations of the bundled valid fixtures. The digest verification on this page runs live
              in your browser using a verbatim copy of the released browser module. The browser and Python sources
              are different implementations, not a byte-identical port.
            </p>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="kicker" style={{ marginBottom: 24 }}>Release artifacts</div>
          <div className="downloads">
            <div className="download">
              <a href={releaseUrl}>GitHub Release — Candidate v0.1.1</a>
              <small>
                Complete ZIP archive, release manifest, SHA-256 digest ledgers, specification PDF, wheel, schemas,
                conformance vectors, and verification evidence. Released July 19, 2026.
              </small>
            </div>
            <div className="download">
              <a href={reviewIssueUrl}>Request for Review — standing invitation</a>
              <small>
                The most useful contribution right now is a demonstration that something in the candidate is wrong,
                ambiguous, or breakable. Defect reports, negative tests, and independent implementations are
                credited.
              </small>
            </div>
            <div className="download">
              <a href={specUrl}>Technical specification v0.1.1</a>
              <small>
                The normative candidate document. Implementing from the specification alone — without reading the
                reference code — is one of the most valuable forms of review.
              </small>
            </div>
            <div className="download">
              <a href={claimsUrl}>Public claim guide</a>
              <small>
                The bounded set of supported public descriptions for this release, including the claims this page
                deliberately does not make.
              </small>
            </div>
          </div>
        </div>
      </section>

      <section className="section alt">
        <div className="container">
          <div className="boundary-note">
            <strong>Claim boundary:</strong> This is a candidate specification, not an adopted standard,
            certification program, external audit, or legal-compliance determination. The SHA-256 digest
            demonstrates content integrity only relative to a trusted expected digest or trusted receipt channel;
            receipts in v0.1.1 are self-attested. Digest verification does not authenticate an issuer, establish key
            custody, provide revocation, or define a production signature suite — issuer authentication, key
            management, and signature profiles are reserved for v0.2 or a dedicated production profile. Receipt
            conformance does not establish that a recorded action was truthful, fair, lawful, safe, or correct.
          </div>
        </div>
      </section>
    </main>
  );
}
